### PR TITLE
Comms/thomas.kost/network layer

### LINKED ISSUE #64: Stop and wait ARQ architecture
Add acks to mqtt link to allow for reliable comms and to ensure messages are recieved whenever a user joins. Also ensure allows for individual and group chatting.

### PR DESCRIPTION
**Pull request by thomaskost17**
# Headline Feature 
This push adds functionality for MQTT server to use ACKS. The current architecture allows for a link to send and receive data. This data can be sent without any guarantee that the receiver is listening and ensures that the the receiver will get all missing data when they again listen. This structure also ensures that repeated messages are not returned as well. Additionally, the sender receiver architecture allows us to easily filter out all   irrelevant data.

## Additional changes
The code ahs been changed to ensure that the listening loop is not a blocking thread--so we do not need to worry about listening impeding any events.

closes #64

### CODE REVIEW

**Comment by nzani** [comment]
Good update for threading. Did you add in messaging from back-end, i.e. are the messages that pop up as a result of the link object? I had set this up before so that certain messages (such as 'type message here') would pop up due to the message_placer object (see src/imgproc/message_placer.py). Not a prob if it did, just gotta know.

**Comment by thomaskost17** [comment]
@nzani Have not added integration for popping up, left it with same implementation of printing as I saw in the previous setup, so assumed it is being grabbed that way

**Review by nzani — CHANGES_REQUESTED** [review]
Still assuming .json format
Include possibility for user **color** and **emoji ID**, which may be arbitrarily tied to gestures or other inputs. Essentially, just add a color and emoji field to the general .json packet.

**Comment by thomaskost17** [comment]
> Still assuming .json format
> Include possibility for user **color** and **emoji ID**, which may be arbitrarily tied to gestures or other inputs. Essentially, just add a color and emoji field to the general .json packet.

commit added this functionality. upon recieving a message the network is updated and information about each user can be accessed by using `get_Color` and `get_Emoji_Tag`

**Review by nzani — APPROVED** [review]
Looks good, some small changes should be made after we do some testing and attempted implementation of MQTT with PyQt, and also for extra functionality to incorporate gesture signaling

**Pull request merged**
